#!/usr/bin/env node
// Syncs the upstream C pixel kernels into src/Compositor.Native/c and regenerates the
// export module definition. Run on every upstream sync (see docs/SYNC-UPSTREAM.md):
//
//   node scripts/sync-native.mjs [path-to-upstream-Rendering-folder]
//
// The kernels are copied verbatim with ONE deterministic patch: DitherPixels.c uses
// Apple's dispatch_apply with block literals, which MSVC cannot compile. The patch
// rewrites in_bands call sites into a plain single-band serial loop and strips the
// __block qualifier — semantically identical (the bands exist only for parallelism).
// If a future upstream change adds new blocks/dispatch usage, this script fails
// loudly instead of producing a broken build.

import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync }
  from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const upstream = process.argv[2] ?? join(root, '..', 'Compositor', 'Compositor', 'Rendering');
const target = join(root, 'src', 'Compositor.Native', 'c');

mkdirSync(target, { recursive: true });
for (const f of readdirSync(target)) rmSync(join(target, f));

for (const f of readdirSync(upstream)) {
  if (!/\.(c|h)$/.test(f)) continue;
  let text = readFileSync(join(upstream, f), 'utf8');
  if (f === 'DitherPixels.c') text = patchDither(text, f);
  else if (/dispatch|__block|\^\s*\(/.test(text)) {
    console.error(`${f}: unexpected blocks/dispatch usage — extend the patch script first`);
    process.exit(1);
  }
  writeFileSync(join(target, f), text);
}

// Exports: one function name per prototype in the headers (module .def keeps the C
// sources verbatim — no __declspec(dllexport) edits needed).
const names = [];
for (const f of readdirSync(target).sort()) {
  if (!f.endsWith('.h')) continue;
  for (const m of readFileSync(join(target, f), 'utf8')
    .matchAll(/(?:^|\n)(?:int|void|long|size_t|float|double|uint8_t|int32_t)\s+\*?([a-z_][a-z0-9_]*)\s*\(/g))
    names.push(m[1]);
}
const def = `; Generated by scripts/sync-native.mjs — do not edit by hand.\nLIBRARY Compositor.Native\nEXPORTS\n`
  + [...new Set(names)].sort().map(n => `    ${n}`).join('\n') + '\n';
writeFileSync(join(root, 'src', 'Compositor.Native', 'Compositor.Native.def'), def);
console.log(`Copied ${readdirSync(target).length} kernel files, exported ${new Set(names).size} functions.`);

function patchDither(text, file) {
  // 1. Drop the Apple header.
  text = text.replace('#include <dispatch/dispatch.h>\n', '');

  // 2. Drop the in_bands helper (comment through its brace-balanced body).
  const start = text.indexOf('// Runs `body` over `count`');
  if (start < 0) throw `${file}: in_bands comment not found`;
  let i = text.indexOf('{', text.indexOf('static void in_bands', start)), depth = 0;
  for (; i < text.length; i++) {
    if (text[i] === '{') depth++;
    else if (text[i] === '}') { depth--; if (!depth) break; }
  }
  text = text.slice(0, start) + text.slice(i + 1);

  // 3. Strip __block qualifiers (safe: the patched loop is serial).
  text = text.replaceAll('__block ', '');

  // 4. Rewrite each call site:
  //      in_bands(EXPR, ^(size_t A, size_t B) { ...body... });
  //    into a serial single-band block:
  //      { size_t A = 0, B = (EXPR); do { ...body... } while (0); in_bands_done_N: ; }
  //    A block-literal `return;` exits just that band; at any nesting depth the exact
  //    serial equivalent is `goto` past the band, which do/while+label provides. A
  //    `return value;` inside a band has no equivalent and fails the sync loudly.
  let out = '', at = 0, count = 0;
  const call = /in_bands\((.+), \^\(size_t (\w+), size_t (\w+)\) \{/g;
  const balance = (s) => {
    let b = 0, p = 0;
    for (const c of s) { if (c === '{') b++; else if (c === '}') b--; if (c === '(') p++; else if (c === ')') p--; }
    return `${b}/${p}`;
  };
  const balanceBefore = balance(text);
  for (let m; (m = call.exec(text));) {
    count++;
    const label = `in_bands_done_${count}`;
    out += text.slice(at, m.index);
    out += `{ size_t ${m[2]} = 0, ${m[3]} = (${m[1]}); do {`;
    at = m.index + m[0].length;
    // Walk to the matching `});` closer of the band body.
    let depth2 = 1, j = at;
    for (; j < text.length; j++) {
      const c = text[j];
      if (c === '{') depth2++;
      else if (c === '}') {
        depth2--;
        if (!depth2 && text.slice(j, j + 3) === '});') break;
        if (!depth2) throw `${file}: unexpected closer after in_bands`;
      } else if (depth2 >= 1 && c === 'r' && text.slice(j, j + 6) === 'return') {
        if (text.slice(j + 6).match(/^\s*;/)) {
          out += text.slice(at, j) + `goto ${label};`;
          at = j + 6 + text.slice(j + 6).match(/^\s*;/)[0].length;
        } else {
          throw `${file}: in_bands body returns a value — needs a manual port`;
        }
      }
    }
    if (j >= text.length) throw `${file}: in_bands closer not found`;
    out += text.slice(at, j) + `} while (0); ${label}: ; }`;
    at = j + 3;
  }
  if (!count) throw `${file}: no in_bands call sites found`;
  out += text.slice(at);
  if (balance(out) !== balanceBefore) throw `${file}: patch changed brace/paren balance`;
  if (/dispatch|__block|\^\s*\(/.test(out)) throw `${file}: blocks syntax survived the patch`;
  return out;
}
